spring:
  application:
    name: moas

  datasource:
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    default-schema: ${DB_SCHEMA}

server:
  port: ${SERVER_PORT}
  error:
    whitelabel:
      enabled: false
