server:
  port: 7777
  shutdown: graceful
  error:
    whitelabel:
      enabled: false
  tomcat:
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: [ "health" ]

spring:
  application:
    name: devnogi-server
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT:3366}/${DB_SCHEMA}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:devnogi}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  resources:
    static-locations: classpath:/static/
  mvc:
    contentnegotiation:
      # URL 확장자에 의한 컨텐트 타입 결정
      favor-path-extension: true
      # Accept 헤더 무시
      ignore-accept-header: true

jwt:
  secret-key: ${JWT_SECRET_KEY:e4f1a5c8d2b7e9f0a6c3d1b8e5f2c7a9d4e6f3b1a2c8d5e9f0b3a7c2d1e8f5a4}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY:3600} # seconds (1 hour)
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY:86400} # seconds (1 day)

springdoc:
  swagger-ui:
    persist-authorization: true
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    classification:
      readyToUseGroupName: 개발 완료 API
      workInProgressGroupName: 개발 진행중 API
      deprecatedGroupName: 더이상 유지보수되지 않는 API

decorator:
  datasource:
    p6spy:
      enable-logging: false

logging:
  config: classpath:logback/logback-display.xml

---
spring:
  config:
    activate:
      on-profile: default

decorator:
  datasource:
    p6spy:
      enable-logging: true

logging:
  level:
    until.the.eternity: DEBUG

openapi:
  nexon:
    api-key: ${NEXON_API_KEY}
  auction-history:
    delay-ms: 1000

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
